# Generated by Django 5.0 on 2023-12-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Тема работы')),
                ('student', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Автор работы')),
                ('score', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Оценка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('teacher', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Научный руководитель')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('shown', models.BooleanField(default=True, verbose_name='Показать в общей таблице?')),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='courseworks/%Y/', verbose_name='Работа в PDF')),
            ],
            options={
                'verbose_name': 'Курсовая работа',
                'verbose_name_plural': 'Курсовые работы',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Тема работы')),
                ('student', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Автор работы')),
                ('score', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Оценка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('teacher', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Научный руководитель')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('shown', models.BooleanField(default=True, verbose_name='Показать в общей таблице?')),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='diplomas/%Y/', verbose_name='Работа в PDF')),
            ],
            options={
                'verbose_name': 'Дипломная работа',
                'verbose_name_plural': 'Дипломные работы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Тема работы')),
                ('student', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Автор работы')),
                ('score', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Оценка')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('teacher', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Научный руководитель')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='Краткое описание')),
                ('shown', models.BooleanField(default=True, verbose_name='Показать в общей таблице?')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='email')),
                ('pdf', models.FileField(blank=True, default='', null=True, upload_to='waitlist/%Y/', verbose_name='Работа в PDF')),
                ('save_as', models.CharField(choices=[('Nothing', 'Не добавлять к работам'), ('Courseworks', 'Курсовые работы'), ('Diplomas', 'Дипломные работы')], default='Nothing', max_length=15, verbose_name='Куда добавить работу?')),
            ],
            options={
                'verbose_name': 'Работа на рассмотрении',
                'verbose_name_plural': 'Работы на рассмотрении',
            },
        ),
    ]
