# Generated by Django 5.0 on 2023-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='score',
            field=models.CharField(blank=True, choices=[('Хорошо', 'Хорошо'), ('Отлично', 'Отлично'), ('Удовлeтворительно', 'Удовлeтворительно'), ('Неудовлeтворительно', 'Неудовлeтворительно')], default='', max_length=255, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='score',
            field=models.CharField(blank=True, choices=[('Хорошо', 'Хорошо'), ('Отлично', 'Отлично'), ('Удовлeтворительно', 'Удовлeтворительно'), ('Неудовлeтворительно', 'Неудовлeтворительно')], default='', max_length=255, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(blank=True, choices=[('Хорошо', 'Хорошо'), ('Отлично', 'Отлично'), ('Удовлeтворительно', 'Удовлeтворительно'), ('Неудовлeтворительно', 'Неудовлeтворительно')], default='', max_length=255, null=True, verbose_name='Оценка'),
        ),
    ]
