version: "3.4"
services:

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: /app/start.sh
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volume:/app/media

  db:
    image: postgres:15.3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d COURSE"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    depends_on:
      - db
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  front:
    build:
      context: .
      dockerfile: front.Dockerfile
    environment:
      - REACT_APP_HOST_IP=http://localhost:8000
    ports:
      - '3000:80'
    depends_on:
      - django

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - django
      - front


volumes:
  postgres_data_volume:
  media_volume:
