# Generated by Django 5.0 on 2023-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время загрузки работы в сервис'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время загрузки работы в сервис'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время загрузки работы в сервис'),
        ),
    ]
